CREATE TABLE EMPLOYEES_ROLE AS SELECT * FROM EMPLOYEES WHERE 1=0;
-- 데이터없이 테이블 구조만 복사

SELECT * FROM EMPLOYEES_ROLE;
SELECT COUNT(*)FROM EMPLOYEES WHERE EMPLOYEE_ID='101';
-- COUNT(*): 전체 DATA 개수

insert into employees_role values(101, 'Neena', 'Kochhar', 'NKOCHHAR', '515.123.4568', '1989-09-21', 'AD_VP', 17000.00, NULL, 100, 90);
insert into employees_role values(101, 'Neena', 'Kochhar', 'NKOCHHAR', '515.123.4568', '1989-09-21', 'AD_VP', 17000.00, NULL, 100, 90);
insert into employees_role values(101, 'Nee', 'Ko', 'NKOCHHAR', '515.123.4568', '1989-09-21', 'AD_VP', 17000.00, NULL, 100, 90);
insert into employees_role values(200, 'Neena', 'Kochhar', 'NKOCHHAR', '515.123.4568', '1989-09-21', 'AD_VP', 17000.00, NULL, 100, 90);
insert into employees_role values(200, 'Nee', 'Kochhar', 'NKOCHHAR', '515.123.4568', '1989-09-21', 'AD_VP', 17000.00, NULL, 100, 90);
insert into employees_role values(300, 'GilDong', 'Hong', 'NKOCHHAR', '010-123-4567', '2009-03-01', 'IT_PROG', 23000.00, NULL, 100, 90);

commit;
-- 동기화


-- EX1
SELECT EMPLOYEE_ID, LAST_NAME FROM EMPLOYEES
UNION
SELECT EMPLOYEE_ID, LAST_NAME FROM EMPLOYEES_ROLE;


-- EX2
SELECT EMPLOYEE_ID, LAST_NAME FROM EMPLOYEES
UNION ALL
SELECT EMPLOYEE_ID, LAST_NAME FROM EMPLOYEES_ROLE;

SELECT SALARY FROM EMPLOYEES WHERE DEPARTMENT_ID=10
UNION ALL
SELECT SALARY FROM EMPLOYEES_ROLE WHERE DEPARTMENT_ID=30 ORDER BY 1;
-- UNION ALL: 자동 정렬 X


-- EX3
SELECT EMPLOYEE_ID, LAST_NAME FROM EMPLOYEES
MINUS
SELECT EMPLOYEE_ID, LAST_NAME FROM EMPLOYEES_ROLE;


-- EX4
SELECT EMPLOYEE_ID, LAST_NAME FROM EMPLOYEES
INTERSECT
SELECT EMPLOYEE_ID, LAST_NAME FROM EMPLOYEES_ROLE;


-- EX5
SELECT LAST_NAME, JOB_TITLE
FROM EMPLOYEES
JOIN JOBS USING(JOB_ID)
WHERE JOB_TITLE IN ('Stoack Manager', 'Programmer');
-- SQL 구문 길이가 짧다고 처리 속도가 빠르다는 보장X

SELECT LAST_NAME, JOB_TITLE
FROM EMPLOYEES
JOIN JOBS USING(JOB_ID)
WHERE JOB_TITLE='Stock Manager'
UNION
SELECT LAST_NAME, JOB_TITLE
FROM EMPLOYEES
JOIN JOBS USING(JOB_ID)
WHERE JOB_TITLE='Programmer'
ORDER BY 2;


-- EX6
SELECT LAST_NAME, EMPLOYEE_ID, HIRE_DATE
FROM EMPLOYEES
WHERE DEPARTMENT_ID=20
UNION
SELECT DEPARTMENT_NAME, DEPARTMENT_ID, NULL
FROM DEPARTMENTS
WHERE DEPARTMENT_ID=20;
-- DEPARTMENT_ID=20인 두 테이블의 합집합
-- RESULT COL: 1번째 SELECT 문장의 COL만 도출


-- 문제1
SELECT FIRST_NAME "사원이름", JOB_ID "업무 ID", DEPARTMENT_ID "부서 ID"
FROM EMPLOYEES
WHERE DEPARTMENT_ID=10
UNION
SELECT FIRST_NAME "사원이름", JOB_ID "업무 ID", DEPARTMENT_ID "부서 ID"
FROM EMPLOYEES_ROLE
WHERE JOB_ID='IT_PROG';
