CREATE TABLE USERIMAGE (
    SEQ          NUMBER          PRIMARY KEY,
    IMAGENAME    VARCHAR2(50)    NOT NULL,
    IMAGECONTENT VARCHAR2(4000),
    IMAGE        VARCHAR2(200)
);

CREATE SEQUENCE SEQ_USERIMGAGE NOCYCLE NOCACHE;

-- UserImgDTO와 동일한 변수명 사용

-- VARCHAR2 MAX_SIZE: 4000