CREATE TABLE PBOARD(
SEQ NUMBER PRIMARY KEY,
NAME VARCHAR2(30),
EMAIL VARCHAR2(30),
HOMEPAGE VARCHAR2(35),
-- 유효성 검사: NOT NULL에 대해서만 진행
SUBJECT VARCHAR2(500) NOT NULL,
CONTENT VARCHAR2(4000) NOT NULL,
LOGTIME DATE);
