-- EX1
CREATE TABLE TEST(
    ID NUMBER(5),
    NAME CHAR(10),
    ADDRESS VARCHAR2(50)
);


-- EX2
CREATE TABLE USER1(
    IDX NUMBER PRIMARY KEY,
    ID VARCHAR2(10) UNIQUE,
    NAME VARCHAR2(10) NOT NULL,
    PHONE VARCHAR2(15),
    ADDRESS VARCHAR2(50),
    SCORE NUMBER(6,2) CHECK(SCORE>=0 AND SCORE<=100),
    SUBJECT_CODE NUMBER(5),
    HIRE_DATE DATE DEFAULT SYSDATE,
    MARRIAGE CHAR(1) DEFAULT 'N' CHECK(MARRIAGE IN('Y', 'N'))
);


-- EX3
SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE
FROM USER_CONSTRAINTS
WHERE TABLE_NAME='USER1';


-- EX4
CREATE TABLE USER2(
    IDX NUMBER CONSTRAINT PKIDX PRIMARY KEY,
    ID VARCHAR2(10) CONSTRAINT UNID UNIQUE,
    NAME VARCHAR2(10) CONSTRAINT NOTNAME NOT NULL,
    PHONE VARCHAR2(15),
    ADDRESS VARCHAR2(50),
    SCORE NUMBER(6,2) CONSTRAINT CKSCORE CHECK(SCORE>=0 AND SCORE<=100),
    SUBJECT_CODE NUMBER(5),
    HIRE_DATE DATE DEFAULT SYSDATE,
    MARRIAGE CHAR(1) DEFAULT 'N' CONSTRAINT CKMARR CHECK(MARRIAGE IN('Y', 'N'))
);


-- EX5
SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE
FROM USER_CONSTRAINTS
WHERE TABLE_NAME='USER2';


-- EX6
INSERT INTO USER1(IDX, ID, NAME, PHONE, ADDRESS, SCORE, SUBJECT_CODE, HIRE_DATE, MARRIAGE)
VALUES(1, 'aaa', 'kim', '010-000-0000','서울',75,100,'2010-08-01','Y');

INSERT INTO USER1(IDX, ID, NAME, PHONE, ADDRESS, SCORE, SUBJECT_CODE, HIRE_DATE, MARRIAGE)
VALUES(1,'aaa','kim','010-000-0000','서울',75,100,'2010-08-01','Y');
-- ORA-00001: 무결성 제약 조건(HR.SYS_C008366)에 위배됩니다

INSERT INTO USER1(IDX, ID, NAME, PHONE, ADDRESS, SCORE, SUBJECT_CODE, HIRE_DATE, MARRIAGE)
VALUES(2,'aaa','kim','010-000-0000','서울',75,100,'2010-08-01','Y');
-- ORA-00001: 무결성 제약 조건(HR.SYS_C008366)에 위배됩니다

INSERT INTO USER1(IDX, ID, NAME, PHONE, ADDRESS, SCORE, SUBJECT_CODE, HIRE_DATE, MARRIAGE)
VALUES(2,'bbb','','010-000-0000','서울',75,100,'2010-08-01','Y');
-- ORA-01400: NULL을 ("HR"."USER1"."NAME") 안에 삽입할 수 없습니다

INSERT INTO USER1(IDX, ID, NAME, PHONE, ADDRESS, SCORE, SUBJECT_CODE, HIRE_DATE, MARRIAGE)
VALUES(2,'bbb','lee','010-000-0000','서울',120,100,'2010-08-01','Y');
-- ORA-02290: 체크 제약조건(HR.SYS_C008364)이 위배되었습니다

INSERT INTO USER1(IDX, ID, NAME, PHONE, ADDRESS, SCORE, SUBJECT_CODE, HIRE_DATE, MARRIAGE)
VALUES(2,'bbb','lee','010-000-0000','서울',75,100,'2010-08-01','K');
-- ORA-02290: 체크 제약조건(HR.SYS_C008364)이 위배되었습니다

INSERT INTO USER1(IDX, ID, NAME, PHONE, ADDRESS, SCORE, SUBJECT_CODE, HIRE_DATE, MARRIAGE)
VALUES(2,'bbb','lee','010-000-0000','서울',75,100,'2010-08-01','N');


-- EX7
SELECT * FROM TAB;


-- EX8
SELECT * FROM USER1;
SELECT * FROM USER2;


-- EX9
DESC USER1;
DESCRIBE USER1;


-- EX10
SELECT * FROM USER_SEQUENCES;


-- EX11
ALTER TABLE USER1 RENAME TO USER3;


-- EX12
ALTER TABLE USER3 ADD PHONE3 VARCHAR2(15);
DESC USER3;


-- EX13
ALTER TABLE USER3 ADD CONSTRAINT PK2 PRIMARY KEY(PHONE);
-- ORA-02261: 고유 키 또는 기본 키가 이미 존재하고 있습니다
-- 02261. 00000 -  "such unique or primary key already exists in the table"
-- *Cause:    Self-evident.
-- *Action:   Remove the extra key.

SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE
FROM USER_CONSTRAINTS
WHERE TABLE_NAME='USER3';


-- EX14
ALTER TABLE USER3 DROP CONSTRAINT UID2;
ALTER TABLE USER3 DROP CONSTRAINT SYS_C008363;

ALTER TABLE USER1 DROP CONSTRAINT SYS_C008363;
-- PK CONTRAINT_NAME: SYS_C008363
ALTER TABLE USER1 ADD ADD_PK PRIMARY KEY(IDX, PHONE);
-- PK 1번 선언, 여러개의 PK COL 지정


-- EX15
ALTER TABLE USER3 ADD NO NUMBER PRIMARY KEY;
-- NUMBER TYPE NO COL을 PK로 추가
DESC USER3;


-- EX16
ALTER TABLE USER3 MODIFY NAME VARCHAR2(10);
DESC USER3;


-- EX17
ALTER TABLE USER3 DROP COLUMN ADDRESS;
DESC USER3;


-- EX18
DROP TABLE USER3;
SELECT * FROM TAB;
PURGE RECYCLEBIN;

DROP TABLE TSET PURGE;
SELECT * FROM TAB;


-- EX19
CREATE SEQUENCE IDX_SEQ INCREMENT BY 2 START WITH 1 MAXVALUE 9 NOCYCLE NOCACHE;
SELECT IDX_SEQ.NEXTVAL FROM DUAL;
SELECT IDX_SEQ.CURRVAL FROM DUAL;

SELECT * FROM USER_SEQUENCES;

DROP SEQUENCE IDX_SEQ;


-- EX20
CREATE TABLE BOOK(
    NO NUMBER PRIMARY KEY,
    SUBJECT VARCHAR2(50),
    PRICE NUMBER,
    YEAR DATE
);

CREATE SEQUENCE NO_SEQ INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE;

INSERT INTO BOOK(NO, SUBJECT, PRICE, YEAR)
VALUES(no_seq.nextval, '오라클 무작정 따라하기', 10000, sysdate);

INSERT INTO BOOK(NO, SUBJECT, PRICE, YEAR)
VALUES(no_seq.nextval, '자바 3일 완성', 15000, '2007-03-01');

INSERT INTO BOOK VALUES(no_seq.nextval, 'JSP 달인 되기', 18000, '2010-01-01');

SELECT * FROM BOOK;


-- EX21
CREATE TABLE USER3 AS (SELECT * FROM USER2 WHERE 1=0);
DESC USER3;

SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, SEARCH_CONDITION
FROM USER_CONSTRAINTS
WHERE TABLE_NAME='USER2';

SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, SEARCH_CONDITION
FROM USER_CONSTRAINTS
WHERE TABLE_NAME='USER3';
-- NOT NULL 제외 CONSTRAINT 복사X, CONSTRAINT ALIAS 복사X


-- EX22
CREATE TABLE USER4(BUNHO, IRUM, JUSO)
AS (SELECT IDX, NAME, ADDRESS FROM USER1 WHERE ID='bbb');

SELECT * FROM USER1;
SELECT * FROM USER4;


-- EX23
CREATE TABLE DEPT(
    DEPTNO NUMBER CONSTRAINT DNO PRIMARY KEY,
    DNAME VARCHAR2(30) CONSTRAINT DANME NOT NULL
);

CREATE TABLE EMP(
    EMPNO NUMBER CONSTRAINT ENO PRIMARY KEY,
    ENAME VARCHAR2(30) CONSTRAINT ENAME NOT NULL,
    DEPTNO NUMBER,
    CONSTRAINT FKNO FOREIGN KEY(DEPTNO) REFERENCES DEPT ON DELETE SET NULL
);

insert into dept(deptno, dname) values(10, '개발부');
insert into dept(deptno, dname) values(20, '영업부');
insert into dept(deptno, dname) values(30, '관리부');
insert into dept(dname) values(40, '경리부');
-- ORA-00913: 값의 수가 너무 많습니다
insert into dept(deptno, dname) values(40, '경리부');

insert into emp(empno, ename, deptno) values(100, '홍길동', 10);
insert into emp(empno, ename, deptno) values(101, '라이언', 20);
insert into emp(empno, ename, deptno) values(102, '튜브', 50); 
-- ORA-02291: 무결성 제약조건(HR.FKNO)이 위배되었습니다- 부모 키가 없습니다

insert into emp(empno, ename, deptno) values(103, '어피치', 40);
insert into emp(empno, ename) values(105, '프로도');
insert into emp(ename, deptno) values('콘', 10);
-- ORA-01400: NULL을 ("HR"."EMP"."EMPNO") 안에 삽입할 수 없습니다

COMMIT;


-- EX24
DELETE FROM DEPT;
SELECT * FROM DEPT;

ROLLBACK;
SELECT * FROM DEPT;

DELETE FROM DEPT WHERE DEPTNO=40;
SELECT * FROM DEPT;
SELECT * FROM EMP;


-- EX25
UPDATE EMP SET DEPTNO=30 WHERE ENAME='프로도';
SELECT * FROM EMP;
COMMIT;
